### ISSUE TITLE
Create dynamic layout for pattern library pages

### ISSUE THREAD

**Issue by juliaelman** [18F/govt-wide-patternlibrary#103]
In Sprint 2, we moved forward with using flat designs for each of the pages. For Sprint 3, we are starting to flesh out these interior pages with their assigned layouts.

**Comment by carodew** [comment]
Adding the wireframes. 

Since we agreed that we'll need to do testing before we know for sure what works best, the team will build out the easier version (to reduce development time before testing) and build out each component page with a single download button. That button will download the files (HTML, CSS, JS if needed) for that component only. Since the download section layout is single column and pretty simple anyway, it will look the same in a mobile view.

![download button desktop](https://cloud.githubusercontent.com/assets/10144074/8410509/af388820-1e4c-11e5-8f12-44180f86a764.png)


Component page with code snippets (use for Accordion only for testing):

![gwpl-desktop-wireframes v2](https://cloud.githubusercontent.com/assets/10144074/8410482/8724b944-1e4c-11e5-9e63-4e156d0ec269.png)
![gwpl-mobile-wireframe v2](https://cloud.githubusercontent.com/assets/10144074/8410490/8f3bc564-1e4c-11e5-8f72-90a00ce5de2f.png)

**Comment by juliaelman** [comment]
Completed, per merge from #112.
