### ISSUE TITLE
update repo name to --> `gov-wide-pattern-library`

### ISSUE THREAD

**Issue by rypan** [18F/govt-wide-patternlibrary#11]
or just `gov-pattern-library`

**Comment by msecret** [comment]
I like `gov-pattern-library`

**Comment by jenniferthibault** [comment]
I had the same thought yesterday when looking at the slack channel name (`govwidepatternlibrary`). My vote goes toward `gov-pattern-library` or `usgov-pattern-library` if it needs to be more specific. `gov-wide` seems nearly redundant. @maya would `usgov` track to some of the very early thoughts on css style naming you mentioned?

**Comment by angel** [comment]
I like gov-pattern-library or usgov-pattern-library as well.

**Comment by maya** [comment]
+1 I like it shorter.

@jenniferthibault yes, the idea is we would namespace classes and prefix them with: `usa-` or `usg-` for example. So you'd have `.usa-header`.

**Comment by jenniferthibault** [comment]
another option: `usa-pattern-library`

**Comment by juliaelman** [comment]
+1 for `usa-pattern-library`

**Comment by maya** [comment]
I suggested that for the URL here: https://github.com/18F/govt-wide-patternlibrary/issues/5#issuecomment-105770048 :)

**Comment by ericronne** [comment]
`usa-pattern-library` strikes me as a good patriotic option :)

`gov-pattern-library` may offer a couple advantages, tho ...
- connotes ".gov"
- the lack of specificity may suggest this work as a standard for other govs (state, local, international) to imitate

**Comment by maya** [comment]
I think @rypan's main point with opening this issue is:

1. That we are using the _t_ in "govt" while not using that in other places. Using just gov is cleaner, nicer, and common practice.
2. Separating "patternlibrary" with a dash between words to be consistent and legible.

So we can at least do that as we decide on a different name. I like both `usa-pattern-library` and `gov-pattern-library`.

Another question, should the repo name be consistent with the actual name? https://github.com/18F/govt-wide-patternlibrary/issues/10

**Comment by mollieru** [comment]
I say let's resolve the repo name first since we're still discussing the
branding of the library.

Since branding/style will be a component of this as well, I wonder what you
guys think of broadening this beyond 'pattern library'...

What do y'all think about "usa-web-patterns-and-styles"?

**Comment by maya** [comment]
Louder Than Ten has something similar - broader than a pattern library, they call theirs "Manual" http://manual.louderthanten.com/

**Comment by carodew** [comment]
Moving into workflow. Thanks for the comments!
