### ISSUE TITLE
Feedback: [Search Results] Remove filetype icons from the search results page

### ISSUE THREAD

**Issue by afeijoo** [18F/govt-wide-patternlibrary#120]
Icons slow down the page load time, interfere with scanning the results, and shifts the snippet to the left.

**Comment by Scotchester** [comment]
I agree that they seem misplaced, since they break up the left alignment and interfere with scanning, but I'm not particularly worried about the load time, given that the icon is likely to already be cached by the time a user gets to this page.

It does seem redundant with the "PDF" label to the right of the title, though.

**Comment by colinpmacarthur** [comment]
Thanks so much @afeijoo and @Scotchester! I’ve added this suggestion to our project workflow.
