### ISSUE TITLE
Feature request: Forms

### ISSUE THREAD

**Issue by vz3** [18F/govt-wide-patternlibrary#13]
In the case of openFOIA, we've got medium to large forms:
* For potential future implementation: FOIA request submission. Audience: FOIA requesters.
* Currently being implemented: Contact update form. Audience: Government agencies.

Because the second one is the only one that has been fully fleshed out, I will go into more detail.

## Features+Description

* Many fields, many of which are pre-populated but may need to be edited/updated (label and input field layout become very important here)
* About a 40/60 split required vs optional elements (do we mark optional? do we mark required?)
* Validation of phone numbers, zip codes, email, URLs (how and when do we display errors?)
* For some (yes unfortunate) instances, many dozens of fields to navigate. DOJ for instance has 38-sub agencies, each with 16-17 fields. How do users navigate this? (See [one solution](https://github.com/18F/foia-hub/issues/723#issuecomment-101425567
) in the openFOIA contact updater mockup)
* Contextual information. If a field needs further explanation, how do we show that info?
* Nudges. If a field is optional but we want to nudge users to submit information, how do we do that?

A relatively recent mockup [can be seen on the openFOIA repo](https://github.com/18F/foia-hub/issues/723#issuecomment-101425567). Error messages have been moved to below the fields, as the right side of the fields are used for contextual information.

**Comment by mollieru** [comment]
Thanks @vz3 !  Would like to see more examples of form types/patterns that other teams think would be helpful. Would love to see screenshots from other folks -- specifically from VA, MyUSCIS, FDA, Ed.

**Comment by emilyville** [comment]
Here's an example from the existing application: 
![screen shot 2015-06-08 at 1 28 17 pm](https://cloud.githubusercontent.com/assets/1307774/8120608/f53652bc-1055-11e5-9c8c-bcaf12d042ef.png)

And our (very, very stock bootstrap) replacement of it, or a screen like it. 
https://whispering-dusk-4439.herokuapp.com/
![screen shot 2015-06-11 at 4 24 14 pm](https://cloud.githubusercontent.com/assets/1307774/8120647/60c14442-1056-11e5-95f5-a48a9d536290.png)

**Comment by emilyville** [comment]
And another, that is public facing for people (veterans) to create a resume
http://department-of-veterans-affairs.github.io/employment-center/create.html
![screen shot 2015-06-11 at 4 28 56 pm](https://cloud.githubusercontent.com/assets/1307774/8120718/61c0ceca-1057-11e5-9fd7-93158cb7c90c.png)
![screen shot 2015-06-11 at 4 29 43 pm](https://cloud.githubusercontent.com/assets/1307774/8120719/64b333b6-1057-11e5-987f-6df175fb8749.png)

**Comment by andrewmaier** [comment]
Here's a list of basic form elements that I try and style on most projects:

- input fields
- textareas
- radiobuttons
- select boxes 
- Buttons
- Custom buttons (primary action, cancel buttons, icon buttons)
- Fieldsets (which need custom markup because the browser default is laughable)
- Custom fieldsets (address blocks, phone number blocks, name blocks, date-range blocks)
- Tooltips / help text
- Custom widths
- Success messages
- Error messages
- Error styles
- Disabled styles
- Hover styles (with accessible fallbacks)
- Focus styles

In general, I also try and progressively enhance forms: starting by building things in a way that uses browser-default styles and doesn't require javascript.

**Comment by vz3** [comment]
@emilyville good stuff! those forms look *so much* better!

I love the use of the placeholder text for examples.

Did you consider any other layouts for the label+field relationship? (Left aligned, top-aligned)

**Comment by mollieru** [comment]
@andrewmaier thank you! super helpful! we've started sketching some of those basic form elements, not comprehensive of your list yet, but you can take a peak here: 
https://github.com/18F/govt-wide-patternlibrary/issues/38

Also, alerts and error messages here:
https://github.com/18F/govt-wide-patternlibrary/issues/37

also to echo @vz3 , @emilyville I *also* really like the placeholder text...that seems like a really nice best practice we can communicate!

cc @angel + @carodew

**Comment by emilyville** [comment]
Thanks @mollieru and @vz3! 

I think it is worth creating an emphasis on elegant defaults to put suggestions and help text (i.e. placeholder text, and content that would go in something like tooltips) inline, That way it's easy to avoid hovers and tooltips since they often cause issues later with accessibility across people, browsers, and devices. 

Also feels like this type of helper-content often piles up at the end and wasn't afforded by the original layout/design, so maybe a styleguide could assist in preempting this problem!

**Comment by mollieru** [comment]
Form patterns and elements are well under way and in production. Closing this out for now! Thanks for the input y'all.
