### ISSUE TITLE
[Links] Add a section on links to provide additional guidance

### ISSUE THREAD

**Issue by AccessForAll** [18F/govt-wide-patternlibrary#167]
* Help meet users' expectations when they're navigating: 
     * Pointer: Ensure that when people hover over a link (or give a link focus by keyboard/non-mouse device), the pointer turns into a hand.

**Comment by maya** [comment]
Links already behave like this and explanations can be added via Usage and Accessibility guidance, which have yet to be written out.

**Comment by AccessForAll** [comment]
Yes, I should have been more specific. The pointer should change to a hand over all navigable items (including buttons), which doesn't always happen. Perhaps we can add that guidance to the accessibility section.

**Comment by colinpmacarthur** [comment]
This issue is almost certainly because the current production version of the library (at https://pages.18f.gov/govt-wide-patternlibrary) has pictures of (not the actual versions of) the buttons and other clickable components. Thus, many buttons don't appear clickable yet. This will change as we roll out new versions of the library.

I'm going to close this issue, but feel free to reopen @AccessForAll, if I've misinterpreted the issue you raise.
