### ISSUE TITLE
[Typography] What kind of type treatments/H styles, etc. should we offer?

### ISSUE THREAD

**Issue by mollieru** [18F/govt-wide-patternlibrary#42]
_v1 of components: unbranded basic styling focused on layout, sizing, padding + UX/interaction_

This is _not_ the typography we are suggesting as part of a style guide. This is the typography we are using for v1 of the library, and it will very likely change.  We'd like feedback on the way we've presented the type styles and applications, and not on the typeface itself (I guess unless you really like it, which is helpful too).

![typography_ui_v1](https://cloud.githubusercontent.com/assets/3680494/8219531/b4f70382-1518-11e5-8911-6da057cead89.png)

**Comment by mollieru** [comment]
@angel I think we need a smaller sans serif for things like Breadcrumbs, small disclaimers, etc. (Finding this when trying to use these styles for the Footer)

**Comment by mebates** [comment]
We often use sans serif for body copy, especially for subheader-type content. I would also suggest more space between items in the bulleted list! (Not sure if this is the type of feedback you're looking for right now.)

**Comment by angel** [comment]
@mollieru is header 5 too big? We can add a header 6. Let me know what size you think is would be good. 

@mebates I will look into a sans-serif body option. The list items do feel too close. I have them at a line-height of 22px right now. Thanks for the feedback!

**Comment by angel** [comment]
Here's an updated list: 
![image](https://cloud.githubusercontent.com/assets/103496/8233992/59f75b6e-15a7-11e5-95ea-161c5f00d666.png)

/cc @mebates

**Comment by mebates** [comment]
We have been debating the 75 character line length standard at CFPB as well. @Scotchester has set type in Capital Framework to a max-width of 35em, though it could be closer to 36 or 37 em to match the 75 character standard. We haven't had a thorough debate on how that relates to the grid and if that's the best choice (but we intend to!).

**Comment by noahmanger** [comment]
Don't mind me...just snoopin around the repo, but curious: were you going to do modify the typography at different screen sizes? IMO this is super important, so you don't have enormous headlines with terrible line breaks.

**Comment by maya** [comment]
Snoop around @noahmanger! I think once we get all this in code we'll actively fiddle with screen sizes to make sure it looks good at smaller sizes.

**Comment by carodew** [comment]
+1 re: modifying typography

**Comment by noahmanger** [comment]
FWIW I came across this a while back about responsive typography: http://www.smashingmagazine.com/2014/09/29/balancing-line-length-font-size-responsive-web-design/

**Comment by mollieru** [comment]
THAT is a really handy article. thank you @noahmanger -- super duper interesting.

cc @angel for future iteratings on the font size

**Comment by Scotchester** [comment]
@noahmanger Awesome article! Thanks for sharing it!

**Comment by mollieru** [comment]
@angel I think we need a smaller versions of both serif + sans serif

**Comment by Scotchester** [comment]
A few scattershot questions/comments:

- Consider adding patterns for the following base HTML elements that folks should be able to assume have some base styling:
  - `blockquote`
  - `dl` (definition lists)
  - `h6`
- I suggest increasing the tracking of text set in all caps (i.e., the H5), to improve readability. `letter-spacing: 1px` ought to be sufficient.
- Please show all potential link states (normal, visited, hover, focus, active).
- I recommend avoiding the `border-bottom` technique for your link underlines. [Learn from our mistakes](https://github.com/cfpb/design-manual/issues/244) :wink: That issue describes the technique I'm investigating as a replacement, but have not finished implementing yet.
- Tighten up the list bullets and numbers so they're not hanging a couple pixels into the left margin.
- What will happen to the numbered list numbers if you hit double digits?
- Might be worth showing an example of a list that goes another level deep.
- What's the spacing between two major sections of a page (i.e., the space between an H2 and whatever element precedes it)? We've found we like this to be extra generous (we use 60px), so it's easy to see at a glance how the sections are divided up.
- I would suggest keeping the H4's bottom margin >= 20px, because to me it's odd if you have multiple paragraphs under a heading and the spacing between the paragraphs is greater than the spacing between the heading and the first of those paragraphs.
- Please clarify the heading levels in the example on the right, so it's clear what amount of margin each heading level has.

**Comment by Scotchester** [comment]
Came across this comment in #43:

> "Some large firms and government agencies have security settings that block IE from using webfonts." –@arvalarva

Leaving aside personal feelings on the wisdom of such policy, I am reminded that we should be sure to test any pattern involving a webfont with the fallback font, to ensure that the chosen style doesn't appear broken if the webfont is unavailable.

**Comment by maya** [comment]
@Scotchester for list alignment, how about implementing this technique? https://j.eremy.net/align-lists-flush-left/

**Comment by maya** [comment]
@Scotchester I just implemented that technique here 9950642.

This is what single digit lists will look like:
![screen shot 2015-07-06 at 12 14 28 pm](https://cloud.githubusercontent.com/assets/5249443/8531585/5b56e18e-23dd-11e5-958b-780b77e4cb57.png)

This is what multi-digit lists will look like:
![screen shot 2015-07-06 at 12 14 04 pm](https://cloud.githubusercontent.com/assets/5249443/8531583/5822c406-23dd-11e5-9114-51e7314aa32f.png)

**Comment by Scotchester** [comment]
Looking good! :)

**Comment by carodew** [comment]
Closing this issue and moving into our workflow. Thanks all!
