### ISSUE TITLE
Feedback: Putting all design assets into a single sticker-sheet

### ISSUE THREAD

**Issue by KHarshawat** [18F/govt-wide-patternlibrary#98]
When creating wire-frames or mocks. It would be better if everything was in a single sticker sheet without red-lines. This stickersheet could be organized by forms/buttons/general styles/ and patterns. 

It was super hard bouncing between all the different documents to find an asset I was looking for. It was also challenging to sort through each document and pull out the non-redlined assets or remove the red-lines from them. These redlines are useful as a reference but might be better on the pattern library website or in a separate set of files. Here is a rough stickersheet I created (as PNG)

![usds-stickersheet](https://cloud.githubusercontent.com/assets/6335546/8381253/6744b6d4-1bdf-11e5-8ba8-10a80b62762b.png)

**Comment by mollieru** [comment]
Thanks @KHarshawat ! I think we can do this for you.

**Comment by angel** [comment]
@KHarshawat I put everything into one .ai file, which can be found here: https://drive.google.com/file/d/0B4cLTFDoVvuDcjlJakFLcFd3Z0E. I'll upload it into the assets repo, but before I do I wanted to make sure it's formatted in a helpful manner. Is there anything missing? Are there things I should take out? Do you need guides or things to be in different layers? Let me know. Thanks! /cc @jenniferthibault @mollieru @emilyville @jjoteal

**Comment by KHarshawat** [comment]
@angel looks great! I'll probably continue to have feedback as I use it but for now it looks like everything I'd want :)

**Comment by jjoteal** [comment]
@angel this format works for me!

**Comment by jenniferthibault** [comment]
This is certainly usable! If/when the library gets bigger, I could see it being useful to put separate elements on separate artboards within the same file (in keeping with @KHarshawat 's feedback), though that wouldn't be compatible earlier than Adobe CS5. 

This would likely be for down the line for a final deliverable, but something to pay attention to at that point for max-polished-deliverable-status would be how the .AI doc itself is set up. For example: 
* Use the layers feature and perhaps put one element group per layer, rather than having every element on a single layer.  
![screen shot 2015-07-01 at 6 21 12 pm](https://cloud.githubusercontent.com/assets/11636908/8466253/8517792e-201e-11e5-8238-f07225d45468.png)
* Remove unused color swatches in the swatch panel
![screen shot 2015-07-01 at 6 23 02 pm](https://cloud.githubusercontent.com/assets/11636908/8466260/9973997a-201e-11e5-8f62-76ee0d34bd61.png)
* Set up the document Character & Paragraph styles panel 
* Other things like this that make the file itself easy and ready to use for designers
  *  I could potentially see it being helpful to designers to be able to view the markup showing proportions and spacing, like on the site, even if this was on a locked layer that was default hidden. Having those specs where you're building could mitigate the potential for inconsistencies.  
![screen shot 2015-07-01 at 6 34 26 pm](https://cloud.githubusercontent.com/assets/11636908/8466372/09631d68-2020-11e5-8c07-6045119727b7.png)


(Again, these are way down the line for a more final deliverable, but hope the early feedback is helpful!)

**Comment by mollieru** [comment]
@jenniferthibault suuuuper helpful feedback! will def do more polished prep as you suggest after meaningful iterations to the designs!

**Comment by carodew** [comment]
I'm moving the additional suggestions to the product Ice Box, thanks all!
